language: csharp
solution: NewPlatform.Flexberry.LogService.LogService.sln
dotnet: 3.1
mono: latest
env:
  global:
    - CONFIGURATION: Debug
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
install:
  - nuget restore "NewPlatform.Flexberry.LogService.LogService.sln" -NonInteractive
  - nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory packages
script:
  - msbuild /verbosity:quiet /p:WarningLevel=0 /p:Configuration=$CONFIGURATION "NewPlatform.Flexberry.LogService.LogService.sln"
  - mono ./packages/xunit.runner.console.2.4.1/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.LogService.Tests/bin/$CONFIGURATION/net461/NewPlatform.Flexberry.LogService.Tests.dll
  - dotnet test ./NewPlatform.Flexberry.LogService.Tests/bin/$CONFIGURATION/netcoreapp3.1/NewPlatform.Flexberry.LogService.Tests.dll