# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: NuGet Restore
        run: nuget restore "NewPlatform.Flexberry.LogService.LogService.sln" -NonInteractive
        
      - name: Install xunit.runner.console
        run: nuget install xunit.runner.console -Version 2.4.1 -OutputDirectory testrunner
        
      - name: Compile code
        run:  msbuild /verbosity:quiet /p:WarningLevel=0 /p:Configuration=Debug "NewPlatform.Flexberry.LogService.LogService.sln" 

      - name: Test under mono
        run: mono ./testrunner/xunit.runner.console.2.4.1/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.LogService.Tests/bin/Debug/net461/NewPlatform.Flexberry.LogService.Tests.dll

      - name: Integration test under dotnet core
        run: dotnet test ./NewPlatform.Flexberry.LogService.Tests/bin/Debug/netcoreapp3.1/NewPlatform.Flexberry.LogService.Tests.dll
        