# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, 'release*' ]
  pull_request:
    branches: [ develop, 'release*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  XUNIT_RUNNER: "2.4.1"
  MONO_VERSION: "6.12.0.182"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: NuGet Restore
        run: dotnet restore "NewPlatform.Flexberry.LogService.LogService.sln"
        
      - name: Install xunit.runner.console
        run: nuget install xunit.runner.console -Version $XUNIT_RUNNER -OutputDirectory testrunner
        
      - name: Compile code
        run:  dotnet build --no-restore -v q /p:WarningLevel=0 -c Debug "NewPlatform.Flexberry.LogService.LogService.sln" 

      - name: Integration test under net 10
        run: dotnet test ./NewPlatform.Flexberry.LogService.Tests/bin/Debug/net10.0/NewPlatform.Flexberry.LogService.Tests.dll

      - name: Wait before mono tests (to reduce SIGSEGV risk)
        run: sleep 15

      # В моно есть специфика работы с конфигом, поэтому так просто тесты не отрабатывают.
      - name: Run ReadConnectionStringTest under Mono
        run: mono ./testrunner/xunit.runner.console.$XUNIT_RUNNER/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.LogService.Tests/bin/Debug/net461/NewPlatform.Flexberry.LogService.Tests.dll -method "NewPlatform.Flexberry.LogService.Tests.CustomAdoNetAppenderTest.EncryptDecryptConnectionStringInAppender"

      - name: Run ReadConnectionStringTest under Mono
        run: |
          cp ./NewPlatform.Flexberry.LogService.Tests/Log4net.Configs/App.config ./testrunner/xunit.runner.console.$XUNIT_RUNNER/tools/net461/xunit.console.exe.config
          mono ./testrunner/xunit.runner.console.$XUNIT_RUNNER/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.LogService.Tests/bin/Debug/net461/NewPlatform.Flexberry.LogService.Tests.dll -method "NewPlatform.Flexberry.LogService.Tests.CustomAdoNetAppenderTest.ReadConnectionStringTest"

      - name: Run ReadDefaultConnectionStringTest under Mono
        run: |
          cp ./NewPlatform.Flexberry.LogService.Tests/Log4net.Configs/App.defconnstr.config ./testrunner/xunit.runner.console.$XUNIT_RUNNER/tools/net461/xunit.console.exe.config
          mono ./testrunner/xunit.runner.console.$XUNIT_RUNNER/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.LogService.Tests/bin/Debug/net461/NewPlatform.Flexberry.LogService.Tests.dll -method "NewPlatform.Flexberry.LogService.Tests.CustomAdoNetAppenderTest.ReadDefaultConnectionStringTest"

      - name: Run ReadCustomizationStringsTest under Mono
        run: |
          cp ./NewPlatform.Flexberry.LogService.Tests/Log4net.Configs/App.customizationstrings.config ./testrunner/xunit.runner.console.$XUNIT_RUNNER/tools/net461/xunit.console.exe.config
          mono ./testrunner/xunit.runner.console.$XUNIT_RUNNER/tools/net461/xunit.console.exe ./NewPlatform.Flexberry.LogService.Tests/bin/Debug/net461/NewPlatform.Flexberry.LogService.Tests.dll -method "NewPlatform.Flexberry.LogService.Tests.CustomAdoNetAppenderTest.ReadCustomizationStringsTest"

        